version: '3.8'

services:
  backend:
    container_name: backend_app
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"