version: '3.8'

services:
  backend:
    container_name: backend_app
    build:
      context: ./
      dockerfile: ./app/Dockerfile
      args:
        APP_PORT: ${APP_PORT}
    environment:
      - APP_PORT=${APP_PORT}
    restart: always
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/']
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    volumes:
      - ./app:/app

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"