version: '3.8'

services:
  backend:
    container_name: backend_app
    build:
      context: ./
      dockerfile: ./app/Dockerfile
      args:
        APP_PORT: ${APP_PORT}
      environment:
      - APP_PORT=${APP_PORT}
    restart: always
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"