"""added comany

Revision ID: a21e0e5ddeda
Revises: 8e44c761d16b
Create Date: 2025-03-25 03:58:28.348300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21e0e5ddeda'
down_revision: Union[str, None] = '8e44c761d16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Enum('hidden', 'visible', name='visibilityenum'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.execute("CREATE TYPE roleenum AS ENUM ('owner', 'admin', 'member', 'viewer')")
    op.add_column('users', sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='roleenum'), nullable=True))
    op.execute("UPDATE users SET role='viewer' WHERE role IS NULL")
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
